/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Budget {
  'id' : bigint,
  'monthly_limit' : number,
  'category' : string,
}
export interface BudgetInput { 'monthly_limit' : number, 'category' : string }
export interface CategorySummary { 'total' : number, 'category' : string }
export interface Expense {
  'id' : bigint,
  'title' : string,
  'date' : string,
  'note' : [] | [string],
  'created_at' : string,
  'payment_method' : [] | [string],
  'category' : string,
  'amount' : number,
}
export interface ExpenseInput {
  'title' : string,
  'date' : string,
  'note' : [] | [string],
  'payment_method' : [] | [string],
  'category' : string,
  'amount' : number,
}
export interface _SERVICE {
  'addExpense' : ActorMethod<[ExpenseInput], bigint>,
  'deleteExpense' : ActorMethod<[bigint], boolean>,
  'getBudgets' : ActorMethod<[], Array<Budget>>,
  'getExpenses' : ActorMethod<[], Array<Expense>>,
  'getMonthlySummary' : ActorMethod<[bigint, bigint], Array<CategorySummary>>,
  'getTodaySpending' : ActorMethod<[], number>,
  'seedSampleData' : ActorMethod<[], undefined>,
  'setBudget' : ActorMethod<[BudgetInput], undefined>,
  'updateExpense' : ActorMethod<[bigint, ExpenseInput], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];