/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ExpenseInput = IDL.Record({
  'title' : IDL.Text,
  'date' : IDL.Text,
  'note' : IDL.Opt(IDL.Text),
  'payment_method' : IDL.Opt(IDL.Text),
  'category' : IDL.Text,
  'amount' : IDL.Float64,
});
export const Budget = IDL.Record({
  'id' : IDL.Nat,
  'monthly_limit' : IDL.Float64,
  'category' : IDL.Text,
});
export const Expense = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'date' : IDL.Text,
  'note' : IDL.Opt(IDL.Text),
  'created_at' : IDL.Text,
  'payment_method' : IDL.Opt(IDL.Text),
  'category' : IDL.Text,
  'amount' : IDL.Float64,
});
export const CategorySummary = IDL.Record({
  'total' : IDL.Float64,
  'category' : IDL.Text,
});
export const BudgetInput = IDL.Record({
  'monthly_limit' : IDL.Float64,
  'category' : IDL.Text,
});

export const idlService = IDL.Service({
  'addExpense' : IDL.Func([ExpenseInput], [IDL.Nat], []),
  'deleteExpense' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getBudgets' : IDL.Func([], [IDL.Vec(Budget)], ['query']),
  'getExpenses' : IDL.Func([], [IDL.Vec(Expense)], ['query']),
  'getMonthlySummary' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(CategorySummary)],
      ['query'],
    ),
  'getTodaySpending' : IDL.Func([], [IDL.Float64], ['query']),
  'seedSampleData' : IDL.Func([], [], []),
  'setBudget' : IDL.Func([BudgetInput], [], []),
  'updateExpense' : IDL.Func([IDL.Nat, ExpenseInput], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ExpenseInput = IDL.Record({
    'title' : IDL.Text,
    'date' : IDL.Text,
    'note' : IDL.Opt(IDL.Text),
    'payment_method' : IDL.Opt(IDL.Text),
    'category' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const Budget = IDL.Record({
    'id' : IDL.Nat,
    'monthly_limit' : IDL.Float64,
    'category' : IDL.Text,
  });
  const Expense = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'date' : IDL.Text,
    'note' : IDL.Opt(IDL.Text),
    'created_at' : IDL.Text,
    'payment_method' : IDL.Opt(IDL.Text),
    'category' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const CategorySummary = IDL.Record({
    'total' : IDL.Float64,
    'category' : IDL.Text,
  });
  const BudgetInput = IDL.Record({
    'monthly_limit' : IDL.Float64,
    'category' : IDL.Text,
  });
  
  return IDL.Service({
    'addExpense' : IDL.Func([ExpenseInput], [IDL.Nat], []),
    'deleteExpense' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getBudgets' : IDL.Func([], [IDL.Vec(Budget)], ['query']),
    'getExpenses' : IDL.Func([], [IDL.Vec(Expense)], ['query']),
    'getMonthlySummary' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(CategorySummary)],
        ['query'],
      ),
    'getTodaySpending' : IDL.Func([], [IDL.Float64], ['query']),
    'seedSampleData' : IDL.Func([], [], []),
    'setBudget' : IDL.Func([BudgetInput], [], []),
    'updateExpense' : IDL.Func([IDL.Nat, ExpenseInput], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };